dist: xenial
sudo: true
language: python
python:
    - '3.6'
cache: pip
install:
    - pip install -U pytest pytest-cov codecov
    - pip install -r requirements.txt
    - pip install -e .
script:
    - pytest ardent/ tests/
after_success:
    - codecov
